# Generated by Django 3.2.7 on 2021-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='blog_subtitle',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='blog_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
