# Generated by Django 3.2.7 on 2021-09-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_myuser_postimagemodel_postmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
