# Generated by Django 3.2.7 on 2021-09-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='post_head_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image'),
        ),
    ]
