# Generated by Django 3.2.7 on 2021-09-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_aboutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarmodel',
            name='title_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
