# Generated by Django 3.2.7 on 2021-09-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_navbarmodel_title_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='text',
            field=models.CharField(blank=True, max_length=299, null=True),
        ),
    ]
