# Generated by Django 3.2.7 on 2021-09-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_alter_aboutmodel_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=14)),
                ('text', models.TextField()),
            ],
        ),
    ]
